---
kind: pipeline
type: docker
name: default

steps:
- commands:
  - nix-shell --run 'make lint'
  image: nixos/nix:2.3
  name: lint

- commands:
  - nix-shell --run 'make test'
  image: nixos/nix:2.3
  name: test

- commands:
  - nix-shell --run 'make build'
  image: nixos/nix:2.3
  name: build
