---
kind: pipeline
type: docker
name: default
trigger:
  event:
    exclude:
    - pull_request

steps:
- name: setup
  image: nixos/nix:2.3
  commands:
  - nix-shell --quiet --run 'make setup'
  - echo -n "latest,preview$DRONE_COMMIT_SHA" > .tags

- name: typecheck
  image: nixos/nix:2.3
  commands:
  - nix-shell --quiet --run 'make typecheck'

- name: lint
  image: nixos/nix:2.3
  commands:
  - nix-shell --quiet --run 'make lint'

- name: test
  image: nixos/nix:2.3
  commands:
  - nix-shell --quiet --run 'make test'

- name: build
  image: nixos/nix:2.3
  commands:
  - nix-shell --quiet --run 'make build'

- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: allgreed/lmap
  when:
    branch:
    - master

- name: deploy
  image: nixos/nix:2.3
  environment:
    NOMAD_URL:
      from_secret: nomad_url
  commands:
  - nix-shell --quiet --run "make deploy VERSION=preview$DRONE_COMMIT_SHA NOMAD_URL=$NOMAD_URL"
  when:
    branch:
    - master

- name: upload coverage report
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
      - "*.xml"
    paths:
      - coverage

---
kind: pipeline
type: docker
name: pr
trigger:
  event:
    - pull_request

steps:
- name: prepare msg
  image: nixos/nix:2.3
  commands:
  - echo -n "Czekirałt&#58; https://github.com/allgreed/lmap/pull/$DRONE_PULL_REQUEST" > msg.tpl

- name: notify
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: telegram_token
    to:
      from_secret: telegram_chat_id
    message_file: msg.tpl
